.\" Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.\" Please adjust this date whenever revising the manpage.
.\" 
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.TH "VIREQ" "1" "October  10, 2009" "Robert James Clay" ""
.SH "NAME"
vireq \- Fidonet/FTN File Request Processor

.SH "DESCRIPTION"
VIREQ/Linux is a Fidonet/FTN file request processor which follows the FC\-0086 SRIF standard.   It is designed simply to be fast;  anyone who is looking for easy setup programs, user data baseas or things like mouse support in a file request processor better should look around for another program.

It supports the wildcards '#' and '?' and file name entries.  The '*' wild card may be used mulitple times in single request entries.  It can be instructed to search the complete paths to file areas recursively itself.
.SH "SEE ALSO"
.BR vimkidx (1),
.SH "AUTHOR"
vireq was written by Volker Imre <Volker@imre.dyndns.org>.
.PP 
This manual page was written by Robert James Clay <jame@rocasa.org>.
